//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace i_Reader_S.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("i_Reader_S.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Background {
            get {
                object obj = ResourceManager.GetObject("Background", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background1 {
            get {
                object obj = ResourceManager.GetObject("background1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background2 {
            get {
                object obj = ResourceManager.GetObject("background2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap background3 {
            get {
                object obj = ResourceManager.GetObject("background3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BottleEmpty {
            get {
                object obj = ResourceManager.GetObject("BottleEmpty", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BottleFull {
            get {
                object obj = ResourceManager.GetObject("BottleFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BottleFull2 {
            get {
                object obj = ResourceManager.GetObject("BottleFull2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BottleFull3 {
            get {
                object obj = ResourceManager.GetObject("BottleFull3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BottleFull4 {
            get {
                object obj = ResourceManager.GetObject("BottleFull4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BottleFull5 {
            get {
                object obj = ResourceManager.GetObject("BottleFull5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap BottleFull6 {
            get {
                object obj = ResourceManager.GetObject("BottleFull6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap button_Black {
            get {
                object obj = ResourceManager.GetObject("button_Black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap button_Black1 {
            get {
                object obj = ResourceManager.GetObject("button_Black1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap button_Black2 {
            get {
                object obj = ResourceManager.GetObject("button_Black2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Button_Normal {
            get {
                object obj = ResourceManager.GetObject("Button_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Button_Normal1 {
            get {
                object obj = ResourceManager.GetObject("Button_Normal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Button_Normal11 {
            get {
                object obj = ResourceManager.GetObject("Button_Normal11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Button_Press {
            get {
                object obj = ResourceManager.GetObject("Button_Press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Button_Press1 {
            get {
                object obj = ResourceManager.GetObject("Button_Press1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 [Doing]切换项目|上一页|下一页|下一样本^[Done]|上一页|下一页|^[Exception]|上一页|下一页|^[Search]发送记录|上一页|下一页|导出记录^[Message]清空记录|上一页|下一页|保存记录^[QC]选择项目|上一月|下一月|导出数据^[Setting]基础设置|项目设置|质控设置|其他^ 的本地化字符串。
        /// </summary>
        internal static string ButtonText {
            get {
                return ResourceManager.GetString("ButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换状态：[1]→[2] 的本地化字符串。
        /// </summary>
        internal static string C0002 {
            get {
                return ResourceManager.GetString("C0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询工作状态 的本地化字符串。
        /// </summary>
        internal static string C0003 {
            get {
                return ResourceManager.GetString("C0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出[n] 的本地化字符串。
        /// </summary>
        internal static string C0004 {
            get {
                return ResourceManager.GetString("C0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复仪器 的本地化字符串。
        /// </summary>
        internal static string C0005_0 {
            get {
                return ResourceManager.GetString("C0005_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停仪器 的本地化字符串。
        /// </summary>
        internal static string C0005_1 {
            get {
                return ResourceManager.GetString("C0005_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开#[n]片仓 的本地化字符串。
        /// </summary>
        internal static string C0010 {
            get {
                return ResourceManager.GetString("C0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启仪器 的本地化字符串。
        /// </summary>
        internal static string C0099 {
            get {
                return ResourceManager.GetString("C0099", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置稀释比例：[1] 卡仓号：[2] 检测头：[3] 读取时间1：[4] 读取时间2：[5] 的本地化字符串。
        /// </summary>
        internal static string C3001 {
            get {
                return ResourceManager.GetString("C3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置#[n]卡仓为工作仓 的本地化字符串。
        /// </summary>
        internal static string C3002 {
            get {
                return ResourceManager.GetString("C3002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置稀释比例为1：[n] 的本地化字符串。
        /// </summary>
        internal static string C3003 {
            get {
                return ResourceManager.GetString("C3003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置读取时间1为[n]秒 的本地化字符串。
        /// </summary>
        internal static string C3004 {
            get {
                return ResourceManager.GetString("C3004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置读取时间2为[n]秒 的本地化字符串。
        /// </summary>
        internal static string C3005 {
            get {
                return ResourceManager.GetString("C3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择#[n]检测头 的本地化字符串。
        /// </summary>
        internal static string C3006 {
            get {
                return ResourceManager.GetString("C3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置滴样量为[n]ul 的本地化字符串。
        /// </summary>
        internal static string C3007 {
            get {
                return ResourceManager.GetString("C3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询#[n]卡仓状态 的本地化字符串。
        /// </summary>
        internal static string C3011 {
            get {
                return ResourceManager.GetString("C3011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看所有仓状态 的本地化字符串。
        /// </summary>
        internal static string C3011_0 {
            get {
                return ResourceManager.GetString("C3011_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启#[n]检测头光源 的本地化字符串。
        /// </summary>
        internal static string C3013 {
            get {
                return ResourceManager.GetString("C3013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭#[n]检测头光源 的本地化字符串。
        /// </summary>
        internal static string C3014 {
            get {
                return ResourceManager.GetString("C3014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取当前工作仓 的本地化字符串。
        /// </summary>
        internal static string C3015 {
            get {
                return ResourceManager.GetString("C3015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常模式 的本地化字符串。
        /// </summary>
        internal static string C3020_0 {
            get {
                return ResourceManager.GetString("C3020_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 混匀液测量模式 的本地化字符串。
        /// </summary>
        internal static string C3020_1 {
            get {
                return ResourceManager.GetString("C3020_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进入休眠 的本地化字符串。
        /// </summary>
        internal static string C3050 {
            get {
                return ResourceManager.GetString("C3050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动 的本地化字符串。
        /// </summary>
        internal static string C3051 {
            get {
                return ResourceManager.GetString("C3051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置休眠时间为[n]秒 的本地化字符串。
        /// </summary>
        internal static string C3052 {
            get {
                return ResourceManager.GetString("C3052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启取样开关 的本地化字符串。
        /// </summary>
        internal static string C3053_0 {
            get {
                return ResourceManager.GetString("C3053_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用取样开关 的本地化字符串。
        /// </summary>
        internal static string C3053_1 {
            get {
                return ResourceManager.GetString("C3053_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新测试 的本地化字符串。
        /// </summary>
        internal static string C3054 {
            get {
                return ResourceManager.GetString("C3054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动灌注稀释液 的本地化字符串。
        /// </summary>
        internal static string C3060 {
            get {
                return ResourceManager.GetString("C3060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动灌注清洗液 的本地化字符串。
        /// </summary>
        internal static string C3061 {
            get {
                return ResourceManager.GetString("C3061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 seq为[1]的样本号修改为[2]，操作用户ID为[3] 的本地化字符串。
        /// </summary>
        internal static string CC01 {
            get {
                return ResourceManager.GetString("CC01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 seq为[1]的样本被删除，操作用户ID为[2] 的本地化字符串。
        /// </summary>
        internal static string CC02 {
            get {
                return ResourceManager.GetString("CC02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #[n]卡仓关闭未扫码，启用上一批号条码 的本地化字符串。
        /// </summary>
        internal static string CC03 {
            get {
                return ResourceManager.GetString("CC03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别到条码扫描器信号： 的本地化字符串。
        /// </summary>
        internal static string CC04 {
            get {
                return ResourceManager.GetString("CC04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一样本号设置为： 的本地化字符串。
        /// </summary>
        internal static string CC05 {
            get {
                return ResourceManager.GetString("CC05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户[1]登录成功 的本地化字符串。
        /// </summary>
        internal static string CC06 {
            get {
                return ResourceManager.GetString("CC06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目切换为： 的本地化字符串。
        /// </summary>
        internal static string CC07 {
            get {
                return ResourceManager.GetString("CC07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Doing]状态^[Done]结果^[Exception]备注^ 的本地化字符串。
        /// </summary>
        internal static string ColumnText {
            get {
                return ResourceManager.GetString("ColumnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 通讯端口被占用 的本地化字符串。
        /// </summary>
        internal static string CommError {
            get {
                return ResourceManager.GetString("CommError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap countdown {
            get {
                object obj = ResourceManager.GetObject("countdown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 当前剩余空间不足10GB，系统将会在下次启动时执行清理; 的本地化字符串。
        /// </summary>
        internal static string D0001 {
            get {
                return ResourceManager.GetString("D0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已执行测试数据清理，清理将不会删除测试结果; 的本地化字符串。
        /// </summary>
        internal static string D0002 {
            get {
                return ResourceManager.GetString("D0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主控端口错误 的本地化字符串。
        /// </summary>
        internal static string D0003_1 {
            get {
                return ResourceManager.GetString("D0003_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二维码端口错误 的本地化字符串。
        /// </summary>
        internal static string D0003_2 {
            get {
                return ResourceManager.GetString("D0003_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 除湿端口错误 的本地化字符串。
        /// </summary>
        internal static string D0003_3 {
            get {
                return ResourceManager.GetString("D0003_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荧光端口错误 的本地化字符串。
        /// </summary>
        internal static string D0003_4 {
            get {
                return ResourceManager.GetString("D0003_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 荧光电机端口错误 的本地化字符串。
        /// </summary>
        internal static string D0003_5 {
            get {
                return ResourceManager.GetString("D0003_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CMOS连接错误 的本地化字符串。
        /// </summary>
        internal static string D0003_6 {
            get {
                return ResourceManager.GetString("D0003_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 除湿数据错误 的本地化字符串。
        /// </summary>
        internal static string D0004 {
            get {
                return ResourceManager.GetString("D0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除样本 的本地化字符串。
        /// </summary>
        internal static string DelSampleButton {
            get {
                return ResourceManager.GetString("DelSampleButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [1]1^[2]2^[3]3^[4]10^[5]20^[6]50^[7]100^[8]200^[9]500^[10]1000^[11]2000^[12]5000^[13]10000^ 的本地化字符串。
        /// </summary>
        internal static string DilutionRatio {
            get {
                return ResourceManager.GetString("DilutionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始液路自检，在进行液面探测功能检验时发生错误 的本地化字符串。
        /// </summary>
        internal static string E2501 {
            get {
                return ResourceManager.GetString("E2501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始液路自检，在检查混匀池时发现混匀池中有残留水，请检查废液泵以及排液管道 的本地化字符串。
        /// </summary>
        internal static string E2502 {
            get {
                return ResourceManager.GetString("E2502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始准备清洗液泵流量检查时，液面探测功能自检出现错误 的本地化字符串。
        /// </summary>
        internal static string E2510 {
            get {
                return ResourceManager.GetString("E2510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液泵流量检查时，出现清洗液供应中断，请更换清洗液后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2511 {
            get {
                return ResourceManager.GetString("E2511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液泵流量检查时，未检测到清洗液注入，请检查清洗液泵后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2512 {
            get {
                return ResourceManager.GetString("E2512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液泵流量检查时，液面探测功能自检出现错误 的本地化字符串。
        /// </summary>
        internal static string E2513 {
            get {
                return ResourceManager.GetString("E2513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液泵流量检查在检测流量时，未检测到液体注入，请检查稀释液泵后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2514 {
            get {
                return ResourceManager.GetString("E2514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始废液泵流量检查时，液面探测功能自检出现错误 的本地化字符串。
        /// </summary>
        internal static string E2520 {
            get {
                return ResourceManager.GetString("E2520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在废液泵流量检测时，取样针未探测到液体，请检查液面探测功能后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2521 {
            get {
                return ResourceManager.GetString("E2521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始准备稀释液流量定标时，液面探测功能自检出现错误 的本地化字符串。
        /// </summary>
        internal static string E2530 {
            get {
                return ResourceManager.GetString("E2530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在稀释液流量定标起始液面高度测量时，检测出液面高度超高，请检重新调整取样针高度后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2531 {
            get {
                return ResourceManager.GetString("E2531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在稀释液流量定标起始液面高度测量时，未探测到液面，请检查稀释液泵后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2532 {
            get {
                return ResourceManager.GetString("E2532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在稀释液流量定标时，稀释液供应中断，请检查和更换稀释液后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2533 {
            get {
                return ResourceManager.GetString("E2533", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在稀释液流量定标液面高度测量时，液面探测功能自检出现错误 的本地化字符串。
        /// </summary>
        internal static string E2534 {
            get {
                return ResourceManager.GetString("E2534", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在稀释液流量定标液面高度测量时，未探测到液面，请检查稀释液泵后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2535 {
            get {
                return ResourceManager.GetString("E2535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 液路自检失败退出 的本地化字符串。
        /// </summary>
        internal static string E2550 {
            get {
                return ResourceManager.GetString("E2550", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 液体探测电极未连接, 请检查液体探测电极连接是否完好 的本地化字符串。
        /// </summary>
        internal static string E2901 {
            get {
                return ResourceManager.GetString("E2901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 液体探测电极受影响，请检查取样针接头处以及清洗头处是否有污染物 的本地化字符串。
        /// </summary>
        internal static string E2902 {
            get {
                return ResourceManager.GetString("E2902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液灌注失败， 请检查清洗液供给，如果供给正常则请重新调试清洗液传感器（1号液路传感器）后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2905 {
            get {
                return ResourceManager.GetString("E2905", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在进行稀释液灌注时，液面探测自检出现异常 的本地化字符串。
        /// </summary>
        internal static string E2906 {
            get {
                return ResourceManager.GetString("E2906", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液灌注过程中检测到混匀池中液体水位超高，请检查废液泵排液状态 的本地化字符串。
        /// </summary>
        internal static string E2907 {
            get {
                return ResourceManager.GetString("E2907", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稀释液灌注失败， 请检查稀释液供给，如果供给正常则请重新调试稀释液传感器（0号液路传感器）后重新运行液路自检程序 的本地化字符串。
        /// </summary>
        internal static string E2910 {
            get {
                return ResourceManager.GetString("E2910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在进行稀释液灌注时，液面探测自检出现异常 的本地化字符串。
        /// </summary>
        internal static string E2911 {
            get {
                return ResourceManager.GetString("E2911", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稀释液灌注过程中检测到混匀池中液体水位超高，请检查废液泵排液状态 的本地化字符串。
        /// </summary>
        internal static string E2912 {
            get {
                return ResourceManager.GetString("E2912", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稀释过程中液体容量异常, 请重试一次, 如果故障还在需要进行液路维护 的本地化字符串。
        /// </summary>
        internal static string E3501 {
            get {
                return ResourceManager.GetString("E3501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]已空, 请添加测试卡后再继续测试 的本地化字符串。
        /// </summary>
        internal static string E3520 {
            get {
                return ResourceManager.GetString("E3520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]打开, 请关闭后再继续测试 的本地化字符串。
        /// </summary>
        internal static string E3521 {
            get {
                return ResourceManager.GetString("E3521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]状态异常不能继续工作, 需要重新维护调试 的本地化字符串。
        /// </summary>
        internal static string E3522 {
            get {
                return ResourceManager.GetString("E3522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取片小车向片仓方向移动时, 片仓异常打开, 请关闭好片仓 的本地化字符串。
        /// </summary>
        internal static string E3525 {
            get {
                return ResourceManager.GetString("E3525", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取片小车从片仓提取试剂片时, 片仓异常打开, 请关闭好片仓 的本地化字符串。
        /// </summary>
        internal static string E3526 {
            get {
                return ResourceManager.GetString("E3526", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取片小车从片仓提取试剂片完成离开时, 片仓异常打开, 请关闭好片仓 的本地化字符串。
        /// </summary>
        internal static string E3527 {
            get {
                return ResourceManager.GetString("E3527", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取片失败 的本地化字符串。
        /// </summary>
        internal static string E3540 {
            get {
                return ResourceManager.GetString("E3540", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液不足 的本地化字符串。
        /// </summary>
        internal static string E3901 {
            get {
                return ResourceManager.GetString("E3901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动灌注清洗液失败, 请检查清洗液供给后按开始键继续 的本地化字符串。
        /// </summary>
        internal static string E3902 {
            get {
                return ResourceManager.GetString("E3902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稀释液不足 的本地化字符串。
        /// </summary>
        internal static string E3903 {
            get {
                return ResourceManager.GetString("E3903", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动灌注稀释液失败, 请检查稀释液供给后按开始键继续 的本地化字符串。
        /// </summary>
        internal static string E3904 {
            get {
                return ResourceManager.GetString("E3904", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Home_Normal {
            get {
                object obj = ResourceManager.GetObject("Home_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Home_Press {
            get {
                object obj = ResourceManager.GetObject("Home_Press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 仪器暂停 的本地化字符串。
        /// </summary>
        internal static string I0105 {
            get {
                return ResourceManager.GetString("I0105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪器恢复 的本地化字符串。
        /// </summary>
        internal static string I0106 {
            get {
                return ResourceManager.GetString("I0106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前状态： 的本地化字符串。
        /// </summary>
        internal static string I0110 {
            get {
                return ResourceManager.GetString("I0110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓湿度：[n]% 片仓温度：[m]℃ 仪器内部温度：[s]℃ 的本地化字符串。
        /// </summary>
        internal static string I0111 {
            get {
                return ResourceManager.GetString("I0111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓忙 的本地化字符串。
        /// </summary>
        internal static string I0112 {
            get {
                return ResourceManager.GetString("I0112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        internal static string I0199 {
            get {
                return ResourceManager.GetString("I0199", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [2]废片仓打开^[253]废片仓关闭^ 的本地化字符串。
        /// </summary>
        internal static string I0200 {
            get {
                return ResourceManager.GetString("I0200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机械部件准备就绪 的本地化字符串。
        /// </summary>
        internal static string I1101 {
            get {
                return ResourceManager.GetString("I1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始液路检查 的本地化字符串。
        /// </summary>
        internal static string I2100 {
            get {
                return ResourceManager.GetString("I2100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液灌注完成 的本地化字符串。
        /// </summary>
        internal static string I2101 {
            get {
                return ResourceManager.GetString("I2101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稀释液灌注完成 的本地化字符串。
        /// </summary>
        internal static string I2102 {
            get {
                return ResourceManager.GetString("I2102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卸片小车初始化完成 的本地化字符串。
        /// </summary>
        internal static string I2103 {
            get {
                return ResourceManager.GetString("I2103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转盘电机初始化完成 的本地化字符串。
        /// </summary>
        internal static string I2104 {
            get {
                return ResourceManager.GetString("I2104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转盘零位初始化完成 的本地化字符串。
        /// </summary>
        internal static string I2107 {
            get {
                return ResourceManager.GetString("I2107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓小车初始化完成 的本地化字符串。
        /// </summary>
        internal static string I2108 {
            get {
                return ResourceManager.GetString("I2108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取样臂升降电机初始化完成 的本地化字符串。
        /// </summary>
        internal static string I2109 {
            get {
                return ResourceManager.GetString("I2109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取样比旋转电机初始化完成 的本地化字符串。
        /// </summary>
        internal static string I2113 {
            get {
                return ResourceManager.GetString("I2113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转盘卸片完成 的本地化字符串。
        /// </summary>
        internal static string I2114 {
            get {
                return ResourceManager.GetString("I2114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓小车存在废片 的本地化字符串。
        /// </summary>
        internal static string I2115 {
            get {
                return ResourceManager.GetString("I2115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓小车清空 的本地化字符串。
        /// </summary>
        internal static string I2116 {
            get {
                return ResourceManager.GetString("I2116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸样泵初始化完成 的本地化字符串。
        /// </summary>
        internal static string I2118 {
            get {
                return ResourceManager.GetString("I2118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 液路检测完成 的本地化字符串。
        /// </summary>
        internal static string I2120 {
            get {
                return ResourceManager.GetString("I2120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示按下吸样按钮 的本地化字符串。
        /// </summary>
        internal static string I3101 {
            get {
                return ResourceManager.GetString("I3101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示准备好吸样 的本地化字符串。
        /// </summary>
        internal static string I3102 {
            get {
                return ResourceManager.GetString("I3102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始吸样 的本地化字符串。
        /// </summary>
        internal static string I3103 {
            get {
                return ResourceManager.GetString("I3103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 吸样完成 的本地化字符串。
        /// </summary>
        internal static string I3104 {
            get {
                return ResourceManager.GetString("I3104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提取卡片 的本地化字符串。
        /// </summary>
        internal static string I3105 {
            get {
                return ResourceManager.GetString("I3105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片就绪 的本地化字符串。
        /// </summary>
        internal static string I3106 {
            get {
                return ResourceManager.GetString("I3106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始混匀 的本地化字符串。
        /// </summary>
        internal static string I3107 {
            get {
                return ResourceManager.GetString("I3107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再次混匀 的本地化字符串。
        /// </summary>
        internal static string I3108 {
            get {
                return ResourceManager.GetString("I3108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始滴样 的本地化字符串。
        /// </summary>
        internal static string I3110 {
            get {
                return ResourceManager.GetString("I3110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反应中 的本地化字符串。
        /// </summary>
        internal static string I3111 {
            get {
                return ResourceManager.GetString("I3111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始测试 的本地化字符串。
        /// </summary>
        internal static string I3112 {
            get {
                return ResourceManager.GetString("I3112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始测试 的本地化字符串。
        /// </summary>
        internal static string I3113 {
            get {
                return ResourceManager.GetString("I3113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试结束 的本地化字符串。
        /// </summary>
        internal static string I3114 {
            get {
                return ResourceManager.GetString("I3114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试结束 的本地化字符串。
        /// </summary>
        internal static string I3115 {
            get {
                return ResourceManager.GetString("I3115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片移出 的本地化字符串。
        /// </summary>
        internal static string I3116 {
            get {
                return ResourceManager.GetString("I3116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [0]当前空闲^[1]当前忙^ 的本地化字符串。
        /// </summary>
        internal static string I3120 {
            get {
                return ResourceManager.GetString("I3120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]打开 的本地化字符串。
        /// </summary>
        internal static string I3130 {
            get {
                return ResourceManager.GetString("I3130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]关闭 的本地化字符串。
        /// </summary>
        internal static string I3131 {
            get {
                return ResourceManager.GetString("I3131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]充足 的本地化字符串。
        /// </summary>
        internal static string I3132 {
            get {
                return ResourceManager.GetString("I3132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]少量 的本地化字符串。
        /// </summary>
        internal static string I3133 {
            get {
                return ResourceManager.GetString("I3133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]用完 的本地化字符串。
        /// </summary>
        internal static string I3134 {
            get {
                return ResourceManager.GetString("I3134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请关闭片仓 的本地化字符串。
        /// </summary>
        internal static string I3135 {
            get {
                return ResourceManager.GetString("I3135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前稀释比例为1:[n] 的本地化字符串。
        /// </summary>
        internal static string I3136 {
            get {
                return ResourceManager.GetString("I3136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前工作仓为#[n] 的本地化字符串。
        /// </summary>
        internal static string I3137 {
            get {
                return ResourceManager.GetString("I3137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前读取时间1为[n]秒 的本地化字符串。
        /// </summary>
        internal static string I3138 {
            get {
                return ResourceManager.GetString("I3138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前读取时间2为[n]秒 的本地化字符串。
        /// </summary>
        internal static string I3139 {
            get {
                return ResourceManager.GetString("I3139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前检测头为#[n] 的本地化字符串。
        /// </summary>
        internal static string I3140 {
            get {
                return ResourceManager.GetString("I3140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前滴样量为[n]ul 的本地化字符串。
        /// </summary>
        internal static string I3141 {
            get {
                return ResourceManager.GetString("I3141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前休眠时间为[n]秒 的本地化字符串。
        /// </summary>
        internal static string I3152 {
            get {
                return ResourceManager.GetString("I3152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 休眠模式关闭 的本地化字符串。
        /// </summary>
        internal static string I3152_1 {
            get {
                return ResourceManager.GetString("I3152_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取样功能关闭 的本地化字符串。
        /// </summary>
        internal static string I3153 {
            get {
                return ResourceManager.GetString("I3153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取样功能开启 的本地化字符串。
        /// </summary>
        internal static string I3154 {
            get {
                return ResourceManager.GetString("I3154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动灌注稀释液开始 的本地化字符串。
        /// </summary>
        internal static string I3160 {
            get {
                return ResourceManager.GetString("I3160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动灌注清洗液开始 的本地化字符串。
        /// </summary>
        internal static string I3161 {
            get {
                return ResourceManager.GetString("I3161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动灌注稀释液完成 的本地化字符串。
        /// </summary>
        internal static string I3162 {
            get {
                return ResourceManager.GetString("I3162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动灌注清洗液完成 的本地化字符串。
        /// </summary>
        internal static string I3163 {
            get {
                return ResourceManager.GetString("I3163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仪器进入休眠状态 的本地化字符串。
        /// </summary>
        internal static string I3190 {
            get {
                return ResourceManager.GetString("I3190", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取样进入休眠状态 的本地化字符串。
        /// </summary>
        internal static string I3191 {
            get {
                return ResourceManager.GetString("I3191", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别到定标二维码信息；产品：[n]  批号：[m] 的本地化字符串。
        /// </summary>
        internal static string labelQRText {
            get {
                return ResourceManager.GetString("labelQRText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称：[n]  批号：[m] 的本地化字符串。
        /// </summary>
        internal static string labelReagentInfoText {
            get {
                return ResourceManager.GetString("labelReagentInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 片仓#[n]打开，请在关闭仓门前扫描二维码 的本地化字符串。
        /// </summary>
        internal static string labelReagentOperationText {
            get {
                return ResourceManager.GetString("labelReagentOperationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统正在初始化 的本地化字符串。
        /// </summary>
        internal static string LoadingStep1 {
            get {
                return ResourceManager.GetString("LoadingStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试前机械部件准备 的本地化字符串。
        /// </summary>
        internal static string LoadingStep2 {
            get {
                return ResourceManager.GetString("LoadingStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试前液路部件准备 的本地化字符串。
        /// </summary>
        internal static string LoadingStep3 {
            get {
                return ResourceManager.GetString("LoadingStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备就绪 的本地化字符串。
        /// </summary>
        internal static string LoadingStep4 {
            get {
                return ResourceManager.GetString("LoadingStep4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Log_Normal {
            get {
                object obj = ResourceManager.GetObject("Log_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Log_Press {
            get {
                object obj = ResourceManager.GetObject("Log_Press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 用户名密码错误，请重试 的本地化字符串。
        /// </summary>
        internal static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样本[1]结果为： 的本地化字符串。
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空闲 的本地化字符串。
        /// </summary>
        internal static string MeachineStatus0 {
            get {
                return ResourceManager.GetString("MeachineStatus0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机械自检 的本地化字符串。
        /// </summary>
        internal static string MeachineStatus1 {
            get {
                return ResourceManager.GetString("MeachineStatus1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 液路自检 的本地化字符串。
        /// </summary>
        internal static string MeachineStatus2 {
            get {
                return ResourceManager.GetString("MeachineStatus2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常 的本地化字符串。
        /// </summary>
        internal static string MeachineStatus255 {
            get {
                return ResourceManager.GetString("MeachineStatus255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测试 的本地化字符串。
        /// </summary>
        internal static string MeachineStatus3 {
            get {
                return ResourceManager.GetString("MeachineStatus3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护 的本地化字符串。
        /// </summary>
        internal static string MeachineStatus4 {
            get {
                return ResourceManager.GetString("MeachineStatus4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [Home]主菜单^[Search]查  询^[QC]质  控^[Setting]设  置^[Message]日  志^[Stop]紧急停止^ 的本地化字符串。
        /// </summary>
        internal static string MenuText {
            get {
                return ResourceManager.GetString("MenuText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Message_Normal {
            get {
                object obj = ResourceManager.GetObject("Message_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Message_Normal1 {
            get {
                object obj = ResourceManager.GetObject("Message_Normal1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Message_Normal2 {
            get {
                object obj = ResourceManager.GetObject("Message_Normal2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Message_Press {
            get {
                object obj = ResourceManager.GetObject("Message_Press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 样本[1]进入测试,测试项目为[2],批号为[3],反应时间为[4] 的本地化字符串。
        /// </summary>
        internal static string NewSampleText {
            get {
                return ResourceManager.GetString("NewSampleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap QC_Normal {
            get {
                object obj = ResourceManager.GetObject("QC_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap QC_Press {
            get {
                object obj = ResourceManager.GetObject("QC_Press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap QCBG {
            get {
                object obj = ResourceManager.GetObject("QCBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 定标二维码信息不正确 的本地化字符串。
        /// </summary>
        internal static string QRError {
            get {
                return ResourceManager.GetString("QRError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Reagentclose {
            get {
                object obj = ResourceManager.GetObject("Reagentclose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 所有可用仓已用完，请添加 的本地化字符串。
        /// </summary>
        internal static string ReagentEmpty {
            get {
                return ResourceManager.GetString("ReagentEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ReagentEmpty1 {
            get {
                object obj = ResourceManager.GetObject("ReagentEmpty1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ReagentFull {
            get {
                object obj = ResourceManager.GetObject("ReagentFull", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ReagentFull2 {
            get {
                object obj = ResourceManager.GetObject("ReagentFull2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ReagentFull3 {
            get {
                object obj = ResourceManager.GetObject("ReagentFull3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ReagentFull4 {
            get {
                object obj = ResourceManager.GetObject("ReagentFull4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Reagentopen {
            get {
                object obj = ResourceManager.GetObject("Reagentopen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 测试中断 的本地化字符串。
        /// </summary>
        internal static string ResultError1 {
            get {
                return ResourceManager.GetString("ResultError1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算异常2 的本地化字符串。
        /// </summary>
        internal static string ResultError10 {
            get {
                return ResourceManager.GetString("ResultError10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质控线异常 的本地化字符串。
        /// </summary>
        internal static string ResultError11 {
            get {
                return ResourceManager.GetString("ResultError11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未检测试管 的本地化字符串。
        /// </summary>
        internal static string ResultError12 {
            get {
                return ResourceManager.GetString("ResultError12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 穿刺失败 的本地化字符串。
        /// </summary>
        internal static string ResultError13 {
            get {
                return ResourceManager.GetString("ResultError13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未探测液面 的本地化字符串。
        /// </summary>
        internal static string ResultError14 {
            get {
                return ResourceManager.GetString("ResultError14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 稀释液不足 的本地化字符串。
        /// </summary>
        internal static string ResultError2 {
            get {
                return ResourceManager.GetString("ResultError2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洗液不足 的本地化字符串。
        /// </summary>
        internal static string ResultError3 {
            get {
                return ResourceManager.GetString("ResultError3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置错误 的本地化字符串。
        /// </summary>
        internal static string ResultError4 {
            get {
                return ResourceManager.GetString("ResultError4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取片失败 的本地化字符串。
        /// </summary>
        internal static string ResultError5 {
            get {
                return ResourceManager.GetString("ResultError5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 卡片移出 的本地化字符串。
        /// </summary>
        internal static string ResultError6 {
            get {
                return ResourceManager.GetString("ResultError6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CMOS禁用 的本地化字符串。
        /// </summary>
        internal static string ResultError7 {
            get {
                return ResourceManager.GetString("ResultError7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fluo禁用 的本地化字符串。
        /// </summary>
        internal static string ResultError8 {
            get {
                return ResourceManager.GetString("ResultError8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计算异常1 的本地化字符串。
        /// </summary>
        internal static string ResultError9 {
            get {
                return ResourceManager.GetString("ResultError9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样本[seq] 的结果为：[result] 的本地化字符串。
        /// </summary>
        internal static string ResultMsg {
            get {
                return ResourceManager.GetString("ResultMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Search_Normal {
            get {
                object obj = ResourceManager.GetObject("Search_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Search_Press {
            get {
                object obj = ResourceManager.GetObject("Search_Press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 样本号|测试项目|结果|测试时间 的本地化字符串。
        /// </summary>
        internal static string SearchResultHearder {
            get {
                return ResourceManager.GetString("SearchResultHearder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Setting_Normal {
            get {
                object obj = ResourceManager.GetObject("Setting_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Setting_Press {
            get {
                object obj = ResourceManager.GetObject("Setting_Press", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap ShowPassword {
            get {
                object obj = ResourceManager.GetObject("ShowPassword", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon SoftWareLogo {
            get {
                object obj = ResourceManager.GetObject("SoftWareLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Stop_Normal {
            get {
                object obj = ResourceManager.GetObject("Stop_Normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 紧急停止确认 的本地化字符串。
        /// </summary>
        internal static string StopTip1 {
            get {
                return ResourceManager.GetString("StopTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复正常状态 的本地化字符串。
        /// </summary>
        internal static string StopTip2 {
            get {
                return ResourceManager.GetString("StopTip2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap switch_off {
            get {
                object obj = ResourceManager.GetObject("switch_off", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap switch_on {
            get {
                object obj = ResourceManager.GetObject("switch_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 无可切换项目，请检查片仓 的本地化字符串。
        /// </summary>
        internal static string SwitchTestItemError {
            get {
                return ResourceManager.GetString("SwitchTestItemError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已关闭片仓，但是未检测到定标二维码信号，系统将会采用产品[n]、批号[m]的历史定标信息。如需扫描二维码请点击确定后重新操作。 的本地化字符串。
        /// </summary>
        internal static string textBoxQRAlertText {
            get {
                return ResourceManager.GetString("textBoxQRAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap topbg {
            get {
                object obj = ResourceManager.GetObject("topbg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
